# Generated by Django 3.1.1 on 2020-09-15 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dockerApp', '0003_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='task_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Task ID'),
            preserve_default=False,
        ),
    ]
