# Generated by Django 3.1.1 on 2020-09-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerApp', '0004_instance_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Status'),
        ),
    ]
